---
title: "NSPY vs SPY"
---

# deps

```{r}
# libraries
library(tidyverse)
library(quantmod)

# dates to pull from (1yr from today)
to = as.Date("2023-07-07")
from = to-365
```

# pulling price data, filtering for our date range, transforming to proper class

```{r}
spy <- getSymbols("SPY", src = "yahoo", auto.assign = FALSE)

spy_prices <- spy %>%
  as.data.frame() %>%
  rownames_to_column(var = "date") %>%
  mutate(ticker = "SPY",
         date = as.Date(date)) %>%
  filter(dplyr::between(date, from, to)) %>%
  select(ticker, date, "open" = 2, "high" = 3, "low" = 4, "close" = 5) %>%
  arrange(ticker, date)

head(spy_prices)
```

# calculating 'spy returns' table
# - hold_return = yesterday's close to today's close return
# - day_return = open to close return 
# - night_return = yesterdays' close to today's open 

```{r}
spy_returns <- spy_prices %>%
  mutate(hold_return = close/lag(close)-1,
         day_return = close/open-1,
         night_return = open/lag(close)-1) %>%
  drop_na()

head(spy_returns)
```

# calculating & plotting pnls

```{r, fig.width=12, fig.height=4}
spy_returns %>%
  mutate(across(ends_with("return"), function(x) cumsum(x))) %>%
  pivot_longer(hold_return:night_return) %>%
  ggplot(aes(x = date, y = value, color = name)) +
  geom_line() +
  facet_wrap(~name, scales = "free") +
  labs(title = "spy returns",
       subtitle = "cumulative spy returns in day, night, & hold periods",
       x = "",
       y = "spy returns (%)")
```

# save data 

```{r}
# write_csv(spy_returns, "data/spy_returns.csv")
```

