---
title: "Recreating Predicting Alpha Gold 2.7"
---

**Loading Libraries**

```{r}
library(tidyverse)
library(quantmod)
library(PortfolioAnalytics)
```

**Setting Variables**

```{r}
set.seed(123)

tickers <- c("XLP", "XLU", "GLD", "SLV", "USDCAD=X", "USDAUD=X")
date_from <- as.Date("2007-01-03")
date_to <- as.Date("2020-11-19")
```

**Pulling Price Data & Calculating Returns**

```{r}
ticker_list <- lapply(1:length(tickers), function(x){
  tbl <- getSymbols(Symbols = tickers[x], src = "yahoo", return.class = "data.frame", auto.assign = FALSE) %>%
    suppressWarnings()
  
  price_tbl <- tbl %>%
    mutate(Date = as.Date(row.names(.), format = "%Y-%m-%d")) %>%
    filter(dplyr::between(Date, date_from, date_to)) %>%
    select(Date, ends_with("Adjusted")) 
  
  names(price_tbl) <- c("Date", tickers[x])
  
  return(price_tbl)
})

return_tbl <- reduce(ticker_list, full_join, by = "Date") %>%
  arrange(Date) %>%
  drop_na() %>%
  mutate(across(where(is.numeric), function(x) ROC(x))) %>%
  drop_na() 

return_tbl <- as.zoo(return_tbl[,!names(return_tbl) %in% "Date"], order.by = return_tbl$Date)
```

**Building Portfolios**

```{r}
port <- NULL

port <- portfolio.spec(names(return_tbl))
port <- add.constraint(port, type = "weight_sum", min_sum = 0.95, max_sum = 1.05)
port <- add.constraint(port, type = "box", min = 0.02, max = 0.6)
port <- add.objective(portfolio = port, type = "return", name = "mean")
port <- add.objective(portfolio = port, type = "risk", name = "StdDev")

optimized_port <- optimize.portfolio(R = return_tbl, portfolio = port, optimize_method = "random", trace = TRUE)

optimized_port
```

**Charting Optimized Portfolio Weights**

```{r}
chart.Weights(optimized_port)
```

**Re-balance Portfolio & Chart Moving Weights**

```{r}
rebalanced_port <- optimize.portfolio.rebalancing(
  R = return_tbl,
  portfolio = port,
  optimize_method = "random",
  rp = random_portfolios(port, 1000, "sample"),
  rebalance_on = "quarters",
  training_period = 252,
  rolling_window = 252)

chart.Weights(rebalanced_port)
```

**Performance Summary: Re-balanced Portfolio & Equal-Weighted Portfolio**

```{r, fig.width=12}
rebalanced_returns <- Return.portfolio(R = return_tbl, extractWeights(rebalanced_port))
names(rebalanced_returns) <- "Strategy"

benchmark <- Return.portfolio(R = return_tbl, weights = rep(1/ncol(return_tbl), ncol(return_tbl)))
names(benchmark) <- "Equal Weight"

port_comp <- na.omit(cbind(rebalanced_returns, benchmark))

charts.PerformanceSummary(port_comp, main = "Performance", geometric = TRUE)
```
